#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${TASK_MANAGER_POSTGRES_USER} WITH PASSWORD '${TASK_MANAGER_POSTGRES_PASSWORD}';
    CREATE DATABASE ${TASK_MANAGER_POSTGRES_DB} OWNER ${TASK_MANAGER_POSTGRES_USER};

EOSQL
